# Generated by Django 4.2.2 on 2023-06-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='detalles',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
